version: '3.8'
services:
  client:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - client_build:/app/dist
    command: sh -c "npm ci && npm run build && cp -r dist/* /app/dist/"
    environment:
      - VITE_API_BASE_URL=https://dcodelabs.studio/
    restart: unless-stopped

  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - client

volumes:
  client_build:
  caddy_data:
  caddy_config:
