version: '3.8'
services:
  client:
    build: .
    restart: unless-stopped
    # Environment variables for build-time (optional)
    # environment:
    #   VITE_API_BASE_URL: https://dcodelabs.studio/
    #   ...
    volumes:
      - client_build:/app/dist

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - client_build:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - client

volumes:
  client_build:
  caddy_data:
  caddy_config:
